version: '3.4'

services:

  aerospikedb:
    image: aerospike/aerospike-server:latest
    command: [ "--config-file","/opt/aerospike/data/aerospike.conf"]
    volumes:
      - ./data:/opt/aerospike/data/
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"


